export const MUTATION_TYPE = {
    INIT_APP_CONTEXT: 'INIT_APP_CONTEXT',
    INIT_APP_CONFIG: 'INIT_APP_CONFIG',
    SET_LABELS: 'SET_LABELS',
    SET_DICTIONARY_NAME: 'SET_DICTIONARY_NAME',
    CACHE_REGION_ANNOTATIONS: 'CACHE_REGION_ANNOTATIONS',
    SET_SELECTED_LABEL: 'SET_SELECTED_LABEL',
    SET_WINDOW_IS_OPEN: 'SET_WINDOW_IS_OPEN',
    SET_THEME: 'SET_DARK_THEME',
};

export const THEMES = {
    DARK: 'DARK',
    LIGHT: 'LIGHT',
    NO_PREFERENCE: 'NO_PREFERENCE',
};